// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkoYv9bSXEWB6_TO0wU6T-ZwBhQHbIjCw',
    appId: '1:546699261245:web:d177eca58a6b7d114d4154',
    messagingSenderId: '546699261245',
    projectId: 'viteats-hackathon',
    authDomain: 'viteats-hackathon.firebaseapp.com',
    storageBucket: 'viteats-hackathon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBymh8tGIDOuXvBnv00p4FohXxpo9qSpxQ',
    appId: '1:546699261245:android:200658d953d30e974d4154',
    messagingSenderId: '546699261245',
    projectId: 'viteats-hackathon',
    storageBucket: 'viteats-hackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBxqxxqqAfiqoYymj70Zg6Qj1Ulc9_ElM',
    appId: '1:546699261245:ios:fe18dc6814b1cd1d4d4154',
    messagingSenderId: '546699261245',
    projectId: 'viteats-hackathon',
    storageBucket: 'viteats-hackathon.appspot.com',
    iosBundleId: 'com.example.viteats',
  );
}
